version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "23:15"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.squareup.leakcanary:leakcanary-android
    versions:
    - "2.5"
    - "2.6"
  - dependency-name: junit:junit
    versions:
    - 4.13.1
